### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by clarsen-007** [dlenski/rsa_ct_kip#10]
Issue -- certificate verify failed: self-signed certificate in certificate chain

As per document  ---  "The server can run either via HTTP or HTTPS. For HTTPS, create a server.pem file in the same directory. It must contain a trusted, signed certificate in order for the RSA SecurID app to connect to it."
This seems to be only for the "Fake server" - but I got certificate from site anyway with --- openssl s_client -connect

It there any way to resolve the certificate issue.

Normal user:
```
$ ./rsa_ct_kip -v https://ccradius.td.XXXXXXXX.com:7004/ctkip/services/CtkipService 001XXXXXXXX key.xml
Sending ClientHello request to server...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ccradius.td.XXXXXXXX.com', port=7004): Max retries exceeded with url: /ctkip/services/CtkipService (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cat/.local/lib/python3.10/site-packages/rsa_ct_kip/client.py", line 223, in main
    token = exchange(args.url, args.activation_code, args.verify, args.verbose, args.hide_secret)
  File "/home/cat/.local/lib/python3.10/site-packages/rsa_ct_kip/client.py", line 130, in exchange
    raw_res1 = s.send(s.prepare_request(req1))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ccradius.td.XXXXXXXX.com', port=7004): Max retries exceeded with url: /ctkip/services/CtkipService (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cat/.local/bin/./rsa_ct_kip", line 8, in <module>
    sys.exit(main())
  File "/home/cat/.local/lib/python3.10/site-packages/rsa_ct_kip/client.py", line 225, in main
    p.exit(1, "Exception in HTTP(S) request: {}\n\t{}\n".format(e.__class__.__name__, '\n\t'.join(e.args)))
TypeError: sequence item 0: expected str instance, MaxRetryError found
```

**Comment by clarsen-007** [comment]
After using -- argument:
-k, --no-verify

Issue was resolved
